FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

# Install application
RUN apt update
RUN apt -y install pandoc python3-pip ffmpeg

# Upgrade pip
RUN pip install --upgrade pip

# Install production dependencies
# COPY ewm/source/requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt

# Install development dependencies
COPY ewm/requirements /tmp/requirements
RUN pip install -r /tmp/requirements/requirements-dev.txt
